### PR TITLE
new plot for newsvendor model in m5 notebook

### PR DESCRIPTION
**Pull request by aagrande**
Adds new plot showing average inventory and demand alongside cumulative profit on the m5 data.

image

### CODE REVIEW

**Comment by ANazaret** [comment]
Great thanks!

**Comment by ANazaret** [comment]
@aagrande can you figure out how to have some of the outputs in the notebook?

**Comment by aagrande** [comment]
@ANazaret thanks, and done!

**Comment by ANazaret** [comment]
beautiful thanks! can you just restart your kernel and re-run all to have the jupyter cell numbered starting at [1].

**Comment by aagrande** [comment]
good catch, merci!

**Pull request merged**
